const parksData = [
    {
        name: "Kenai Fjords National Park",
        state: "Alaska",
        lat: 60.35,
        lng: -149.1,
        website: "https://www.nps.gov/kefj/index.htm",
        airport: "Anchorage Airport (ANC) - 126 miles",
        amtrak: "Seward (Alaska Railroad) -  9 miles",
        shuttle: "Exit Glacier Shuttle",
        intra_transit_score: 2.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 4.0,
        accessibility_rating: 4,
        notes: "Visitors coming from the airport can take either the ACT big bus from the airport or the Alaska Railroad train from Anchorage to Seward. Once in Seward, visitors can take the exit shuttle bus from Seward to Exit Glacier that runs daily from May to September."
    },
    {
        name: "Wrangell-St.Elias National Park",
        state: "Alaska",
        lat: 62.0,
        lng: -142.0,
        website: "https://www.nps.gov/wrst/index.htm",
        airport: "Anchorage Airport (ANC) - 202 miles",
        amtrak: "Anchorage (Alaska Railroad) - 200 miles",
        shuttle: "Kennecott Shuttle service",
        intra_transit_score: 2.0,
        train_score: 0.5,
        ground_transit_score: 0.5,
        seasonality_score: 0.5,
        total_score: 3.5,
        accessibility_rating: 4,
        notes: "Visitors can fly into Anchorage. From Anchorage, they can take the interior Alaska bus line from Anchorage to Glennallen, where they can connect onto a bus to McCarthy, inside the park."
    },
    {
        name: "Denali National Park",
        state: "Alaska",
        lat: 63.3333,
        lng: -150.4972,
        website: "https://www.nps.gov/dena/planyourvisit/basicinfo.htm",
        airport: "Fairbanks Airport (FAI) - 120 miles",
        amtrak: "Denali (Alaska railroad) - right outside the entrance",
        shuttle: "Savage River and Riley Creek Bus Routes",
        intra_transit_score: 1.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 3.0,
        accessibility_rating: 3,
        notes: "Visitors can fly into the Fairbanks airport. From there, they can take a bus into Fairbanks, where they transfer onto the Alaska Railroad, which drops visitors at the bus. Shuttle services once inside the park are free, but only run during summer months."
    },
    {
        name: "Lake Clark National Park",
        state: "Alaska",
        lat: 60.4,
        lng: -153.0,
        website: "https://www.nps.gov/lacl/index.htm",
        airport: "Anchorage Airport (ANC) - 120 miles",
        amtrak: "Anchorage (Alaska railroad) - 100 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.5,
        accessibility_rating: 1,
        notes: "Visitors can fly into Anchorage. From there, they can take an air taxi into the park."
    },
    {
        name: "Gates of the Arctic National Park",
        state: "Alaska",
        lat: 67.75,
        lng: -150.5,
        website: "https://www.nps.gov/gaar/index.htm",
        airport: "Fairbanks airport (FAI) - 277 miles",
        amtrak: "Fairbanks (Alaska Railroad) - 280 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.0,
        accessibility_rating: 1,
        notes: "Visitors can fly into Fairbanks, where they can take charter flights to Coldfoot, Anaktuvuk Pass, or Bettles, where they can access the park either by foot or by air taxi."
    },
    {
        name: "Glacier Bay National Park",
        state: "Alaska",
        lat: 58.5,
        lng: -137.0,
        website: "https://www.nps.gov/glba/index.htm",
        airport: "Juneau Airport (JNU) - 50 miles",
        amtrak: "Prince Rupert station (VIA Rail) - 300 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.0,
        ground_transit_score: 0.5,
        seasonality_score: -0.5,
        total_score: 0.0,
        accessibility_rating: 1,
        notes: "Visitors can fly into Juneau and take a ferry twice a week from Juneau to Gustavus, about 10 miles from the park. Once in Gustavus, transit options are limited."
    },
    {
        name: "Katmai National Park",
        state: "Alaska",
        lat: 58.5,
        lng: -155.5,
        website: "https://www.nps.gov/katm/index.htm",
        airport: "Anchorage Airport (ANC) - 352 miles",
        amtrak: "Anchorage (Alaska railroad) -350 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: -0.5,
        accessibility_rating: 1,
        notes: "Visitors can fly into Anchorage, where they can take a flight to King Salmon, where they can take either a boat or an air taxi into the park."
    },
    {
        name: "Kobuk Valley National Park",
        state: "Alaska",
        lat: 66.8,
        lng: -156.5,
        website: "https://www.nps.gov/kova/index.htm",
        airport: "Kotzebue airport (OTZ) - 103 miles",
        amtrak: "Fairbanks (Alaska Railroad) - 402 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: -0.5,
        accessibility_rating: 1,
        notes: "Visitors can fly from Anchorage to Kotzebue. From Kotzebue, visitors can take an air taxi into the park. Ground transportation is very limited"
    },
    {
        name: "American Samoa National Park",
        state: "American Samoa",
        lat: -14.25,
        lng: -170.6833,
        website: "https://www.nps.gov/npsa/index.htm",
        airport: "Pago Pago Airport (PPG) - 8 miles",
        amtrak: "None",
        shuttle: "None",
        intra_transit_score: 0.5,
        train_score: 0.0,
        ground_transit_score: 1.0,
        seasonality_score: 0.5,
        total_score: 2.0,
        accessibility_rating: 2,
        notes: "Visitors can fly into the Pago Pago airport. From there, they can take a taxi to the national park. Flights to the other islands in the national park are operated by Samoa Airways."
    },
    {
        name: "Grand Canyon National Park",
        state: "Arizona",
        lat: 36.0544,
        lng: -112.1401,
        website: "https://www.nps.gov/grca",
        airport: "Phoenix airport (PHX) - 200miles",
        amtrak: "Flagstaff - 80 miles",
        shuttle: "South Rim Shuttle Routes (5 of them)",
        intra_transit_score: 1.5,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: 0.0,
        total_score: 4.0,
        accessibility_rating: 4,
        notes: "The nearest amtrak station is Flagstaff station (80 miles). There is a Flixbus that runs 5 times a week from Phoenix to the Grand Canyon. Once inside, there is a shuttle service that has 5 routes that run every 10-15 minutes, however only 3 of these routes run year round."
    },
    {
        name: "Petrified Forest National Park",
        state: "Arizona",
        lat: 34.8895,
        lng: -109.7887,
        website: "https://www.nps.gov/pefo/index.htm",
        airport: "Phoenix airport (PHX) - 215 miles",
        amtrak: "Winslow - 30 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest Amtrak station is in Winslow. However, there is no shuttle in the park and no bus service to the park."
    },
    {
        name: "Saguaro National Park",
        state: "Arizona",
        lat: 32.25,
        lng: -110.7333,
        website: "https://www.nps.gov/sagu/index.htm",
        airport: "Tucson airport (TUS) - 10 miles",
        amtrak: "Tucson station- 14 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "Saguaro national park has close connections to both Amtrak and an airport in Tucson. However, there is very limited ground transportation to the park from Tucson."
    },
    {
        name: "Hot Springs National Park",
        state: "Arkansas",
        lat: 34.5126,
        lng: -93.0552,
        website: "https://www.nps.gov/hosp/index.htm",
        airport: "Little Rock (LIT) - 56 miles",
        amtrak: "Malvern station - 21 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Little Rock. From there, visitors take the Texas Eagle to Malvern station, where they take a taxi to Hot Springs national park. There is no shuttle service in Hot Springs national park."
    },
    {
        name: "Yosemite National Park",
        state: "California",
        lat: 37.8651,
        lng: -119.5383,
        website: "https://www.nps.gov/yose",
        airport: "Fresno Airport (FAT) - 60 miles",
        amtrak: "Merced (64 miles)",
        shuttle: "Yosemite Valley Shuttle System",
        intra_transit_score: 2.0,
        train_score: 1.5,
        ground_transit_score: 0.5,
        seasonality_score: 0.5,
        total_score: 4.5,
        accessibility_rating: 4,
        notes: "There is bus service from Merced to Yosemite national park. The nearest amtrak station is in Merced, 64 miles away from the park. The nearest major airport is in Fresno. The Yosemite Valley Shuttle System runs shuttle service from 7am to 10pm every 12 to 22 minutes year round."
    },
    {
        name: "Sequoia National Park",
        state: "California",
        lat: 36.4864,
        lng: -118.5658,
        website: "https://www.nps.gov/seki/index.htm",
        airport: "Fresno Airport (FAT) - 80 miles",
        amtrak: "Hanford station - 55 miles",
        shuttle: "Seasonal shuttle",
        intra_transit_score: 2.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 4.0,
        accessibility_rating: 4,
        notes: "The nearest Major airport to Sequoia National park is in Fresno. From there, visitors can take the greyhound to Visalia, where they can transfer onto the Visalia bus into the park. Once in the park, a free, seasonal shuttle operates 5 routes within the park."
    },
    {
        name: "Channel Islands national park",
        state: "California",
        lat: 34.0109,
        lng: -119.4194,
        website: "https://www.nps.gov/chis/index.htm",
        airport: "Los Angeles (LAX) - 70 miles",
        amtrak: "Ventura station - 5 miles",
        shuttle: "Island Packers",
        intra_transit_score: 1.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: 0.0,
        total_score: 3.5,
        accessibility_rating: 4,
        notes: "The nearest major airport is LAX. From there, visitors can take a Central Coast Shuttle bus to Ventura or they can take the Pacific Surfliner up to Ventura. From there, they can take ticketed boats operated by Island Packers to the islands. The Santa Cruz and Anacapa Island boat services run year round, while service for the other islands runs seasonally."
    },
    {
        name: "Joshua Tree National Park",
        state: "California",
        lat: 33.8734,
        lng: -115.901,
        website: "https://www.nps.gov/jotr/index.htm",
        airport: "Palm Springs airport (PSP) - 25 miles",
        amtrak: "Palm Springs station - 50 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 2.0,
        accessibility_rating: 2,
        notes: "The nearest major airport and Amtrak stations are in Palm Springs, California. From there, visitors can take the Basin Transit bus to the outskirts of the park. However, there is no shuttle service once inside the park."
    },
    {
        name: "Pinnacles National Park",
        state: "California",
        lat: 36.48,
        lng: -121.1695,
        website: "https://www.nps.gov/pinn/index.htm",
        airport: "San Jose airport (SJC) - 80 miles",
        amtrak: "Salinas station - 35 miles",
        shuttle: "Shuttle service",
        intra_transit_score: 1.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 2.0,
        accessibility_rating: 2,
        notes: "The nearest major airport is in San Jose. From there, visitors can take a bus to Salinas, where they can connect onto a bus that takes them to San Vicente. From there, there is limited public transport. In the park, there is shuttle service that runs during the spring."
    },
    {
        name: "Kings Canyon National park",
        state: "California",
        lat: 36.8035,
        lng: -118.6155,
        website: "https://www.nps.gov/seki/planyourvisit/kings-canyon-national-park.htm",
        airport: "Fresno Airport (FAT) - 82 miles",
        amtrak: "Hanford station - 35 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.5,
        seasonality_score: -0.5,
        total_score: 1.5,
        accessibility_rating: 2,
        notes: "The nearest major airport is in Fresno. From there, visitors can take the greyhound to the Visalia transit station, where they can then take the sequoia shuttle to the outskirts of the park. However, once in the park, transit is very limited."
    },
    {
        name: "Redwood National and State Parks",
        state: "California",
        lat: 41.2132,
        lng: -124.0046,
        website: "https://www.nps.gov/redw/index.htm",
        airport: "Rogue Valley Airport (MFR) - 159 miles",
        amtrak: "Klamath Falls station - 178 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 1.5,
        accessibility_rating: 2,
        notes: "The nearest major airport is rogue valley airport in Oregon. From there, visitors can take a bus to the park transferring at Gasquet market. However, transit options are limited once in the park."
    },
    {
        name: "Lassen Volcanic National Park",
        state: "California",
        lat: 40.4917,
        lng: -121.5071,
        website: "https://www.nps.gov/lavo/index.htm",
        airport: "Sacramento Airport (SMF) - 165 miles",
        amtrak: "Redding station - 50 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Sacramento. From there, visitors can take amtrak up to Reading, but that's where their options end. There is no public transit into the park or inside the park."
    },
    {
        name: "Death Valley National park",
        state: "California, Nevade",
        lat: 36.5323,
        lng: -116.8625,
        website: "https://www.nps.gov/deva/index.htm",
        airport: "Las Vegas airport (LAS) - 120 miles",
        amtrak: "Bakersfield station- 246 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.0,
        accessibility_rating: 1,
        notes: "The nearest major airport to Death Valley national park is in Las Vegas. The nearest Amtrak station is in Bakersfield. Ground transportation from those locations are very limited."
    },
    {
        name: "Rocky Mountain Natinoal Park",
        state: "Colorado",
        lat: 40.3569,
        lng: -105.6955,
        website: "https://www.nps.gov/romo/index.htm",
        airport: "Denver airport (DEN) - 85 miles",
        amtrak: "Gransby station - 20 miles",
        shuttle: "Rocky's Shuttles",
        intra_transit_score: 2.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 4.0,
        accessibility_rating: 4,
        notes: "The closest major airport is in Denver. The closest Amtrak station is in Gransby. From Denver, visitors can take the Bustang bus to the park. Inside of the park, there is shuttle service from June to October."
    },
    {
        name: "Black Canyon Of The Gunnison National Park",
        state: "Colorado",
        lat: 38.5775,
        lng: -107.725,
        website: "https://www.nps.gov/blca/index.htm",
        airport: "Grand Junction Airport (GJT) - 57 miles",
        amtrak: "Grand Junction station - 71.5 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest airport and train station to Black Canyon of the Gunnison National park are in Grand Junction. From there, ground transportation is very limited."
    },
    {
        name: "Mesa Verde National Park",
        state: "Colorado",
        lat: 37.2308,
        lng: -108.4618,
        website: "https://www.nps.gov/meve/index.htm",
        airport: "Albuquerque International Airport (ABQ) - 250 miles",
        amtrak: "Gallup station - 146 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.5,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Albuquerque. The nearest train station is in Gallup. From Albuquerque and Gallup, there are limited transportation options that get visitors into the park."
    },
    {
        name: "Great Sand Dunes National Park",
        state: "Colorado",
        lat: 37.7916,
        lng: -105.5943,
        website: "https://www.nps.gov/grsa/index.htm",
        airport: "Denver airport (DEN) - 257 miles",
        amtrak: "Denver station - 234 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.0,
        accessibility_rating: 1,
        notes: "The nearest major airport and train stations are in Denver. Once in Denver, there are very limited options to reach the park."
    },
    {
        name: "Biscayne National Park",
        state: "Florida",
        lat: 25.2008,
        lng: -80.1806,
        website: "https://www.nps.gov/bisc/index.htm",
        airport: "Miami (MIA) - 31 miles",
        amtrak: "Miami station (38 miles)",
        shuttle: "Homestead Trolley",
        intra_transit_score: 1.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: 0.0,
        total_score: 2.5,
        accessibility_rating: 2,
        notes: "The nearest major airport and amtrak stations are in Miami. There are bus connections, however they require multiple transfers. The Homestead trolley runs seasonally in Biscayne national park from november to april and is ticketed"
    },
    {
        name: "Dry Tortugas National Park",
        state: "Florida",
        lat: 24.6281,
        lng: -82.8737,
        website: "https://www.nps.gov/drto/index.htm",
        airport: "Key West Airport (EYW) - 70 miles",
        amtrak: "Miami station (160 miles)",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 0.5,
        seasonality_score: 0.5,
        total_score: 2.0,
        accessibility_rating: 2,
        notes: "The nearest major airport is in Key West. From Key West, visitors can take the Yankee Freedom Ferry to access Dry Tortugas national park. From Miami, visitors can take the Greyhound to Big Pine Key, where they can connect onto a Key West Transit bus to get to the Ferry,"
    },
    {
        name: "Everglades national park",
        state: "Florida",
        lat: 25.3891,
        lng: -80.7128,
        website: "https://www.nps.gov/ever/index.htm",
        airport: "Miami (MIA) - 43 miles",
        amtrak: "Miami station (56 miles)",
        shuttle: "Homestead Trolley",
        intra_transit_score: 0.5,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: 0.0,
        total_score: 2.0,
        accessibility_rating: 2,
        notes: "The nearest major airport is in Miami. The nearest amtrak station is also in Miami. The Homestead trolley is very limiting, as it is seasonal and is ticketed."
    },
    {
        name: "Haleakala National Park",
        state: "Hawaii",
        lat: 20.797,
        lng: -156.1548,
        website: "https://www.nps.gov/hale/index.htm",
        airport: "Kahului airport (OGG) - 22 miles",
        amtrak: "None",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: -0.5,
        accessibility_rating: 1,
        notes: "Visitors can fly into the nearest major airport in Kahului. From there, there is limited ground transit to the national park and within the national park."
    },
    {
        name: "Hawaii Volcanoes National Park",
        state: "Hawaii",
        lat: 19.3651,
        lng: -155.2942,
        website: "https://www.nps.gov/havo/index.htm",
        airport: "Hilo airport (ITO) - 30 miles",
        amtrak: "None",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: -0.5,
        accessibility_rating: 1,
        notes: "Visitors can fly into Hilo airport. From there, there is limited ground transit to the park and within the park."
    },
    {
        name: "Indiana Dunes National Park",
        state: "Indiana",
        lat: 41.6533,
        lng: -87.0524,
        website: "https://www.nps.gov/indu/index.htm",
        airport: "Midway Airport (MDW) - 52 miles",
        amtrak: "Dune Park station - direct access to the park",
        shuttle: "None",
        intra_transit_score: 1.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: 0.0,
        total_score: 3.5,
        accessibility_rating: 4,
        notes: "The nearest major airport to Indiana Dunes national park is Midway airport. From there, visitors can take the orange line to the Harold Washington library station, where they can then take the South Shore Line from Van Buren and get off at either Dune Park station, Beverly shores station, or Ogden Dunes station. Visitors can use the south shore line between different parts of the park, but there is no official shuttle within the park."
    },
    {
        name: "Mammoth Caves National Park",
        state: "Kentucky",
        lat: 37.1864,
        lng: -86.1001,
        website: "https://www.nps.gov/maca/index.htm",
        airport: "Louisville (SDF) - 90 miles, Nashville (BNA) - 100 miles",
        amtrak: "Fulton station (183 miles)",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 1.5,
        accessibility_rating: 2,
        notes: "The 2 nearest major airports to Mammoth Caves national park are in Nashville and Louisville. From Nashville, take the Memphis Tornado bus from Nashville to Smiths Grove. From Louisville, take the Tropical Tornado bus from Louisville to Smiths Grove. However, once at the park, options are very limited."
    },
    {
        name: "Acadia National Park",
        state: "Maine",
        lat: 44.3386,
        lng: -68.2733,
        website: "https://www.nps.gov/acad",
        airport: "Bangor (BGR) - 46mi",
        amtrak: "Brunswick (135 miles)",
        shuttle: "Island Explorer",
        intra_transit_score: 1.0,
        train_score: 1.0,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 2.5,
        accessibility_rating: 2,
        notes: "There is a direct bus service from the Bangor airport to Bar Harbor. From Bar Harbor, visitors can take the Island Explorer around Acadia national park. The Island Explorer runs every 30-60 minutes and runs seasonally from the late spring into the fall. The nearest amtrak station is Brunswick, about 135 miles from the park. Visitors coming from there can take a bus to Bangor and connect onto a bus to Bar Harbor."
    },
    {
        name: "Isle Royale National Park",
        state: "Michigan",
        lat: 47.955,
        lng: -88.5667,
        website: "https://www.nps.gov/isro/index.htm",
        airport: "Thunder Bay Airport (YQT) - 50 miles",
        amtrak: "None",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.0,
        ground_transit_score: 0.5,
        seasonality_score: -0.5,
        total_score: 0.0,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Thunder Bay, Ontario. There are no buses to the ferry services that transport people into the park. Those services leave from Grand Portrage, Minnesota, Copper Harbor, Michigan, and Houghton, Michigan. Once inside the park, there is very limited transit inside of the park."
    },
    {
        name: "Voyageurs National Park",
        state: "Minnesota",
        lat: 48.5,
        lng: -89.25,
        website: "https://www.nps.gov/voya/index.htm",
        airport: "Falls airport (INL) - 15 miles",
        amtrak: "Sioux Lookout station (VIA rail) - 180 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.5,
        accessibility_rating: 1,
        notes: "The nearest commercial airport to Voyageurs national park is Falls Aiport. Ground transport into the park is very limited. There is water taxi service on demand once in the park."
    },
    {
        name: "Gateway National Park",
        state: "Missouri",
        lat: 38.627,
        lng: -90.1895,
        website: "https://www.nps.gov/jeff/index.htm",
        airport: "St. Louis (STL) - 15 miles",
        amtrak: "St. Louis Gateway station (1 mile)",
        shuttle: "None",
        intra_transit_score: 2.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: 0.5,
        total_score: 5.0,
        accessibility_rating: 5,
        notes: "The Gateway Arch is within walking distance of the amtrak station. From the airport, take the St.Louis lightrail and it will drop you right at the gateway arch national park. There is no shuttle service needed since the park is so small."
    },
    {
        name: "Glacier National Park",
        state: "Montana",
        lat: 48.7596,
        lng: -113.9039,
        website: "https://www.nps.gov/glac",
        airport: "Kalispell (FCA) - 30mi",
        amtrak: "West Glacier and East Glacier (at the park)",
        shuttle: "Logan Pass Shuttle Service",
        intra_transit_score: 1.0,
        train_score: 1.5,
        ground_transit_score: 0.5,
        seasonality_score: -0.5,
        total_score: 2.5,
        accessibility_rating: 2,
        notes: "There is direct amtrak service to glacier national park at east glacier and west glacier stations. The nearest airport is Kalispell airport. From there, visitors would take a taxi to Whitefish station, where they would take the Empire Builder to the park. The Logan Pass Shuttle runs from July 1st to Labor Day and is ticketed."
    },
    {
        name: "Great Basin National Park",
        state: "Nevada",
        lat: 38.9897,
        lng: -114.2181,
        website: "https://www.nps.gov/grba/index.htm",
        airport: "Salt Lake City airport (SLC) - 235 miles",
        amtrak: "Salt Lake City - 235 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.0,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Salt Lake City, Utah. From there, transit options to and inside the park are very limited."
    },
    {
        name: "White Sands National Park",
        state: "New Mexico",
        lat: 32.7791,
        lng: -106.171,
        website: "https://www.nps.gov/whsa/index.htm",
        airport: "El Paso airport (ELP) - 85 miles",
        amtrak: "El Paso station - 85 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest major airport and train stations is in El Paso. From there, there's limited public transit to the park and inside the park."
    },
    {
        name: "Carlsbad Caverns National Park",
        state: "New Mexico",
        lat: 32.1396,
        lng: -104.5853,
        website: "https://www.nps.gov/cave/index.htm",
        airport: "El Paso Airport (ELP) - 150 miles",
        amtrak: "El Paso station - 150 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.5,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Lubbock, Texas. The nearest train station is in El Paso. From there, public transit options into the park and inside of the park are limited."
    },
    {
        name: "Great Smoky Mountains National Park",
        state: "North Carolina/Tennessee",
        lat: 35.5175,
        lng: -83.5008,
        website: "https://www.nps.gov/grsm/index.htm",
        airport: "Knoxville (TYS) - 35 miles",
        amtrak: "Greenville station (88 miles)",
        shuttle: "Multiple private services",
        intra_transit_score: 1.5,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: 0.0,
        total_score: 3.0,
        accessibility_rating: 3,
        notes: "The nearest major airport is in Knoxville. From Knoxville, visitors can take a wide variety of private shuttle services that run from march through october."
    },
    {
        name: "Theodore Roosevelt National Park",
        state: "North Dakota",
        lat: 47.4858,
        lng: -103.4308,
        website: "https://www.nps.gov/thro/index.htm",
        airport: "Dickinson airport (DIK) - 40 miles",
        amtrak: "Williston station - 60 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest commercial airport is in Dickinson. The nearest train station is in Williston. From both locations, there's limited public transportation to the national park and inside the national park."
    },
    {
        name: "Cuyahoga Valley National Park",
        state: "Ohio",
        lat: 41.3411,
        lng: -81.5469,
        website: "https://www.nps.gov/cuva/index.htm",
        airport: "Cleveland (CLE) - 25 miles, Akron-Canton (CAK) -  26 miles",
        amtrak: "Cleveland station (22 miles)",
        shuttle: "Cuyahoga Valley Scenic Railroad",
        intra_transit_score: 1.5,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: 0.5,
        total_score: 4.5,
        accessibility_rating: 4,
        notes: "There are 2 major airports that are within spitting distance of the national park from Cleveland and Akron. From Cleveland, take the flixbus to Akron, then take the Akron metro bus to the park."
    },
    {
        name: "Crater Lake National Park",
        state: "Oregon",
        lat: 42.9446,
        lng: -122.109,
        website: "https://www.nps.gov/crla/index.htm",
        airport: "Medford airport (MFR) - 75 miles",
        amtrak: "Klamath Station - 70 miles",
        shuttle: "Crater Lake Trolley",
        intra_transit_score: 1.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 2.0,
        accessibility_rating: 2,
        notes: "The nearest major airport is in Medford, whereas the nearest train station is in Klamath. From there, there's limited public transportation to the park. However, once inside the park, there is a seasonal trolley service that runs from the visitors center to the campground and back for $10 each way."
    },
    {
        name: "Congaree National Park",
        state: "South Carolina",
        lat: 34.8023,
        lng: -81.1494,
        website: "https://www.nps.gov/cong/index.htm",
        airport: "Charlotte (CLT) - 111 miles",
        amtrak: "Columbia (20 miles)",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Charlotte. The nearest amtrak station is in Columbia, 20 miles away. There is limited bus service to the park and no internal shuttle system."
    },
    {
        name: "Wind Cave National Park",
        state: "South Dakota",
        lat: 43.557,
        lng: -103.4788,
        website: "https://www.nps.gov/wica/index.htm",
        airport: "Rapid City Airport (RAP) - 65 miles",
        amtrak: "Fort Morgan station - 283 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.0,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Rapid City. From there, transit into and inside of the park is very limited."
    },
    {
        name: "Badlands National Park",
        state: "South Dakota",
        lat: 43.7844,
        lng: -102.3006,
        website: "https://www.nps.gov/badl/index.htm",
        airport: "Rapid City Airport (RAP) - 55 miles",
        amtrak: "Fort Morgan station (320 miles)",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: -0.5,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Rapid City. There are very limited transit options to Badlands."
    },
    {
        name: "Big Bend National Park",
        state: "Texas",
        lat: 29.25,
        lng: -103.25,
        website: "https://www.nps.gov/bibe/index.htm",
        airport: "Midland airport (MAF) - 200 miles",
        amtrak: "Alpine station - 100 miles",
        shuttle: "Bend Mountain Bike Shuttle",
        intra_transit_score: 0.5,
        train_score: 1.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Midland, Texas. The nearest Amtrak station is in Alpine, Texas. Transit to the park is limited. The only intra-park transit is the season mountain bike shuttle that runs from July to October."
    },
    {
        name: "Guadalupe Mountains National Park",
        state: "Texas",
        lat: 31.8933,
        lng: -104.8671,
        website: "https://www.nps.gov/gumo/index.htm",
        airport: "El Paso airport (ELP) - 104 miles",
        amtrak: "El Paso station - 100 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.5,
        accessibility_rating: 1,
        notes: "The closest major airport and train stations are in El Paso, Texas. From there, there is limited transit into and around the park."
    },
    {
        name: "Virgin Islands National Park",
        state: "U.S. Virgin Islands",
        lat: 18.3358,
        lng: -64.759,
        website: "https://www.nps.gov/viis/index.htm",
        airport: "St. Thomas airport (STT) - 10 miles",
        amtrak: "None",
        shuttle: "Vitran Bus system",
        intra_transit_score: 2.0,
        train_score: 0.0,
        ground_transit_score: 0.5,
        seasonality_score: -0.5,
        total_score: 2.0,
        accessibility_rating: 2,
        notes: "The closest major airport to Virgin Islands national park is in St. Thomas. From there, visitors can take a ferry to St. John's island, where they can use the Vitran Bus system to get around the island. However, the bus only runs during the week."
    },
    {
        name: "Zion National Park",
        state: "Utah",
        lat: 37.2982,
        lng: -112.9789,
        website: "https://www.nps.gov/zion",
        airport: "Las Vegas (LAS) - 170mi",
        amtrak: "Provo (225 miles)",
        shuttle: "Zion Canyon shuttle system",
        intra_transit_score: 2.0,
        train_score: 0.5,
        ground_transit_score: 0.5,
        seasonality_score: 0,
        total_score: 3.0,
        accessibility_rating: 3,
        notes: "Zion has a fast and frequent shuttle system called the Zion Canyon Shuttle that runs year round. The nearest amtrak station is in Provo. The national park express shuttle runs from Las Vegas to the national park."
    },
    {
        name: "Arches National Park",
        state: "Utah",
        lat: 38.6622,
        lng: -109.5759,
        website: "https://www.nps.gov/arch/index.htm",
        airport: "Salt Lake City airport (SLC) - 230 miles",
        amtrak: "Green River (50 miles)",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The closest airport is in Slat Lake City. The closest train station is in Green River. From there, there is ground transit to Moab, but limited ground transit into and around the park from there."
    },
    {
        name: "Bryce Canyon National Park",
        state: "Utah",
        lat: 37.5763,
        lng: -112.1871,
        website: "https://www.nps.gov/brca/index.htm",
        airport: "Las Vegas airport (LAS) - 270 miles",
        amtrak: "Flagstaff station - 200 miles",
        shuttle: "Bryce Canyon Shuttle",
        intra_transit_score: 2.0,
        train_score: 0.5,
        ground_transit_score: 1.0,
        seasonality_score: 0.0,
        total_score: 3.5,
        accessibility_rating: 4,
        notes: "The closest major airport to Bryce Canyon National park is in Las Vegas. From there, visitors can take the National park express to Bryce Canyon National park. From there, they can take the Bryce Canyon shuttle within the park that runs from April to October."
    },
    {
        name: "Canyonlands National Park",
        state: "Utah",
        lat: 38.2919,
        lng: -109.8787,
        website: "https://www.nps.gov/cany/index.htm",
        airport: "Salt Lake City Airport (SLC) - 237 miles",
        amtrak: "Green River station - 60 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The closest major airport is in Salt Lake City, and the closest train station is in Green River. From there, transit options are limited to get to the park, and there is no shuttle service inside of the park."
    },
    {
        name: "Capitol Reef National Park",
        state: "Utah",
        lat: 38.2008,
        lng: -111.2615,
        website: "https://www.nps.gov/care/index.htm",
        airport: "Salt Lake City airport (SLC) - 228 miles",
        amtrak: "Helper station - 100 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.0,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.5,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Salt Lake City. The nearest Amtrak station is in Helper, Utah. From there, transit to the park is limited and there is no shuttle service inside of the park."
    },
    {
        name: "Shenandoah National Park",
        state: "Virginia",
        lat: 38.5209,
        lng: -78.3589,
        website: "https://www.nps.gov/shen/index.htm",
        airport: "Washington Dulles International Airport (IAD) - 56 miles",
        amtrak: "Charlottesville station (25 miles)",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.5,
        seasonality_score: -0.5,
        total_score: 1.5,
        accessibility_rating: 2,
        notes: "There is an amtrak station nearby in Charlottesville. From Dulles, visitors can take the Virginia Breeze flight to Shenandoah National Park with one transfer."
    },
    {
        name: "Mount Rainier national park",
        state: "Washington",
        lat: 46.8523,
        lng: -121.7603,
        website: "https://www.nps.gov/mora/index.htm",
        airport: "Seattle airport (SEA) - 65 miles",
        amtrak: "Tacoma station - 58 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 1.0,
        accessibility_rating: 1,
        notes: "The nearest major airport is in Seattle, while the nearest Amtrak station is in Tacoma. From there, transit options to get to the park are limited, and transit inside the park is limited as well."
    },
    {
        name: "North Cascades National Park",
        state: "Washington",
        lat: 48.4009,
        lng: -121.2181,
        website: "https://www.nps.gov/noca/index.htm",
        airport: "Seattle airport (SEA) - 110 miles",
        amtrak: "Mount Vernon station - 70 miles",
        shuttle: "Stehekin Shuttle",
        intra_transit_score: 1.5,
        train_score: 1.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 2.5,
        accessibility_rating: 2,
        notes: "The nearest major airport is in Seattle, while the nearest Amtrak station is in Mount Vernon. From there, transit options to the park are limited. Once in the park, visitors can use the seasonal Stekehin shuttle that runs along the Stehekin valley road."
    },
    {
        name: "Olympic National Park",
        state: "Washington",
        lat: 47.979,
        lng: -124.7314,
        website: "https://www.nps.gov/olym/index.htm",
        airport: "Seattle airport (SEA) - 145 miles",
        amtrak: "Seattle station - 140 miles",
        shuttle: "Clallam Transit system",
        intra_transit_score: 2.0,
        train_score: 1.0,
        ground_transit_score: 1.0,
        seasonality_score: 0.0,
        total_score: 4.0,
        accessibility_rating: 4,
        notes: "The nearest major airport and train stations are in Seattle. From there, visitors can take the Dungeness line to Port Angeles, and then take Clallam transit buses to get around the park."
    },
    {
        name: "New River Gorge National Park",
        state: "West Virginia",
        lat: 37.95,
        lng: -81.07,
        website: "https://www.nps.gov/neri/index.htm",
        airport: "Charleston airport (CRW) - 60 miles",
        amtrak: "Thurmond station, Hinton station, and Prince station- at the park",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 1.5,
        ground_transit_score: 1.0,
        seasonality_score: -0.5,
        total_score: 2.0,
        accessibility_rating: 2,
        notes: "The closest major airport is in Charleston, West Virginia. From there, visitors can take the Cardinal to either Thurmond, Hinton, or Prince stations, which all have access to the park. From there, there is limited shuttle service around the park."
    },
    {
        name: "Grand Teton National Park",
        state: "Wyoming",
        lat: 43.7904,
        lng: -110.6818,
        website: "https://www.nps.gov/grte/index.htm",
        airport: "Jackson Hole airport (JAC) - inside of the park",
        amtrak: "Odgen station (Frontrunner) - 255 miles",
        shuttle: "Guest shuttle",
        intra_transit_score: 1.5,
        train_score: 0.5,
        ground_transit_score: 1.0,
        seasonality_score: 0.0,
        total_score: 3.0,
        accessibility_rating: 3,
        notes: "Jackson Hole airport is inside the national park. Visitors staying at the Jackson Lake Lodge and Cotler Bay Village can take a complementary shuttle around the park during May to October."
    },
    {
        name: "Yellowstone National Park",
        state: "Wyoming/Montana/Idaho",
        lat: 44.6275,
        lng: -110.4955,
        website: "https://www.nps.gov/yell/index.htm",
        airport: "Jackson Hole airport (JAC) - 50 miles",
        amtrak: "Ogden Station (Frontrunner) - 286 miles",
        shuttle: "None",
        intra_transit_score: 0.0,
        train_score: 0.5,
        ground_transit_score: 0.0,
        seasonality_score: -0.5,
        total_score: 0.0,
        accessibility_rating: 1,
        notes: "The nearest major airport to Yellowstone National park is in Jackson Hole, Wyoming. From there, transit options are limited to the park and inside the park."
    },
];
